### PR TITLE
fix: login

### LINKED ISSUE #61: Login page
- [x] Allow user to login
- [x] When logged in, do not show the register and login links in the navigation.
- [x] Show logout link
- [x] Clicking logout invalidates the session, hides the logout button, and shows register and login links again

### PR DESCRIPTION
**Pull request by schalkneethling**
Allow a user to log in and logout

As mentioned on Slack, I am simply clearing the token from `localStorage` as I am not sure whether there is a need to actually call the back-end. If we do need to, then I believe the docs needs to be updated to indicate how credentials are to be passed.

I reckon I still need to redirect the user to `/services/` once successfully logged out and in so, will update the PR soon with that as well.

fix #61

### CODE REVIEW

File: src/js/components/account/login.js [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+  getLabel,
+  getSubmitButton,
+} from "../../utils/element-factory";
+
+export class Login {
+  constructor() {
+    const $successTemplate = $(".styles .form-styles .w-form-done").clone();
+    const $failTemplate = $(".styles .form-styles .w-form-fail").clone();
+
+    const defaultBaseUrl = "https://muni-portal-backend.openup.org.za";
```
Comment (jbothma) [inline src/js/components/account/login.js:16]: why are we hardcoding this again? Can't we use the API which allows for overriding this for dev and staging?

File: src/js/components/account/login.js [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+    const endPoint = "/api/accounts/login/";
+    const fields = [
+      {
+        label: "login",
```
Comment (jbothma) [inline src/js/components/account/login.js:20]: this isn't label, this is name - is this just a quick hack to get things working?
