### PR TITLE
fix: add notice index and notice pages

### LINKED ISSUE #78: Create notices landing page
Create landing page for notices from municipality.

### PR DESCRIPTION
**Pull request by schalkneethling**
Add NoticeIndex page as well as page for displaying individual notices

fix #78

### CODE REVIEW

File: src/js/index.js [hunk 1]
```diff
@@ -113,6 +114,11 @@ class App {
         view: this.viewAdministrationIndex.bind(this),
         viewType: "Administration landing",
       },
+      {
+        path: new RegExp("^/my-municipality/notices/$"),
```
Comment (jbothma) [inline src/js/index.js:118]: why a dedicated route for this and not just use the class-based view approach for this?

File: src/js/components/pages.js [hunk 2]
```diff
@@ -348,3 +352,53 @@ export class Service {
...
+    this.breadcrumbItems = getBreadcrumbsWithLabel(content.ancestor_pages);
+    this.noticeMainContent = content.body_html;
+    this.publicationDate = content.publication_date;
+  }
+
+  render() {
+    return [
+      new Breadcrumbs(this.breadcrumbItems).render(),
+      new SectionHeading("Overview").render(),
+      new ExpandableRichText(this.noticeMainContent).render(),
```
Comment (jbothma) [inline src/js/components/pages.js:399]: Let's use the non-expanding version of this - it should be in the component library - I don't think collapsing makes sense for notices that are like microblogs

File: src/js/components/pages.js [hunk 3]
```diff
@@ -348,3 +352,53 @@ export class Service {
...
+      new SectionHeading("Publication Date").render(),
+      timeElem(this.publicationDate),
```
Comment (jbothma) [inline src/js/components/pages.js:401]: Instead of a heading, can we put the date at the top inside the rich text block without a heading as in the mockup?

File: src/js/components/pages.js [hunk 4]
```diff
@@ -348,3 +352,53 @@ export class Service {
...
+    this.breadcrumbItems = getBreadcrumbsWithLabel(content.ancestor_pages);
+    this.childPages = content.child_pages;
+  }
+
+  renderChildPageLinks() {
+    const childPageLinks = this.childPages.map((page) => {
+      const props = {
+        title: page.title,
+        url: page.url,
+        subtitle: "",
```
Comment (jbothma) [inline src/js/components/pages.js:367]: subtitle was supposed to be the publication date, according to the mockup, wasn't it?

File: src/js/components/pages.js (hunk 3 above)
Comment (schalkneethling) [reply src/js/components/pages.js:401]: I have not seen the mock-up :) will have a look. Is it inside the Figma document?

**Comment by schalkneethling** [comment]
Ah, I found the design:

Screenshot 2020-12-14 at 09 59 22

File: src/js/index.js (hunk 1 above)
Comment (schalkneethling) [reply src/js/index.js:118]: True, I reckon I can follow the same pattern I did for the `core.NoticePage`

File: src/js/components/pages.js (hunk 3 above)
Comment (jbothma) [reply src/js/components/pages.js:401]: Sorry, I've been blasting you with slack messages and hoping you'd update the issues and trello as needed

Comment (jbothma) [reply src/js/components/pages.js:401]: https://openupsa.slack.com/archives/C0189R440L9/p1607685421033900

https://openupsa.slack.com/archives/C0189R440L9/p1607685450034300
