### PR TITLE
fix: user registration

### LINKED ISSUE #56: Registration page
Add a registration page:

URL: `/accounts/register`
API: https://openup.gitbook.io/cape-agulhas-app/api/accounts

- [x] Check if components and demo for page exists in latest Webflow export
- [x] Form contains username, password, email address.
- [x] Submit form to the registration API
- [x] Show message to user on success: "Your details have been submitted. Check your email and follow the instructions to complete registration."

### Setup landing pages for

- [x] /accounts/verify-registration/

- that should redirect yo to the frontend /accounts/verify-registration/ where you can parse the query string parameters that you need to AJAX POST to the registration verify endpoint
- and either show the user "registration succeeded. you can now login" or "registration failed. Please try again or contact support"

- [x] /accounts/reset-password/
- [ ] /accounts/verify-email/

### PR DESCRIPTION
**Pull request by schalkneethling**
Add base for user registration to MyMuni.

As I say "base" 😄  We probably want to do more work and offer better feedback depending on the type of error. But this is a start. I also create the entire form using jQuery and add the relevant classes.

Let me know your thoughts.

## Form

Screenshot 2020-11-17 at 12 48 22

## Success

This uses the relevant element from `.styles`

Screenshot 2020-11-17 at 13 01 08

## Fail

This uses the relevant element from `.styles`

Screenshot 2020-11-17 at 13 01 28

fix #56

### CODE REVIEW

File: src/js/components/user-registration.js [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+
+  getInput(type, label) {
+    const name = label.split(" ").join("_");
+    return $("<input />", {
+      class: "card input-field w-input",
+      type: type,
+      name: name,
+      id: `registration-${label}`,
+    });
+  }
```
Comment (jbothma) [inline src/js/components/user-registration.js:85]: isn't there an input we can clone?

Comment (schalkneethling) [reply src/js/components/user-registration.js:85]: There is, but I will have to change all of these attributes so, I reckon this is cheaper than sticking our fingers in the DoM, changing the element, and then sticking it back in somewhere else 😄
